version: '3'
networks:
    internal_network:
      driver: bridge
      
services:
    bus-timing:
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            - internal_network

        working_dir: /go/src/bus-timing
        command: |
            sh -c 'go run main.go'
        expose:
            - "8080"
        ports:
            - "8080:8080"
        volumes:
            - ./:/go/src/bus-timing
